### ISSUE TITLE
Too much dust

### ISSUE THREAD

**Issue by Davide-DD** [iFedix/Dustman#1]
Where's the dustman? Fuck.

**Comment by AndywinXp** [comment]
I can confirm that; also, I was promised a panno swiffer, where's my panno swiffer? That's incredible... I want my money back.

**Comment by AndywinXp** [comment]
![hd450x300](https://user-images.githubusercontent.com/11290886/63794134-8ed53b00-c901-11e9-9bfe-85e8c1ab6f72.jpg)
I ceci sono legumi che con la loro genuinità e dolcezza si prestano alla preparazione di ricette molto diverse fra loro, da quelle legate a tradizioni regionali come la farinata di ceci, tipica della cucina ligure, a ricette più rustiche come la zuppa di ceci, fino ad antipasti o secondi sfiziosi come la frittata al forno ai ceci o l'hamburger di ceci. Se avete voglia di un bel piatto di pasta che racchiuda ingredienti semplici ma allo stesso tempo gustosi e saporiti, vi proponiamo una ricetta della tradizione italiana, dal buon sapore di una volta: la pasta e ceci! Un piatto che sicuramente avrete portato almeno una volta sulla vostra tavola, magari nella classica versione “in bianco”. Noi però vi suggeriamo una deliziosa variante con l’aggiunta della passata di pomodoro e della pancetta, che regaleranno un tocco in più alla ricetta, creando uno sfizioso contrasto con il sapore delicato dei ceci. Non vi resta quindi che provare questa appetitosa e succulenta versione della pasta e ceci, che con la sua genuina bontà saprà scaldarvi nelle sere più fredde dell'inverno!

**Comment by Davide-DD** [comment]
But Dustman doesn't like pasta e ceci... Che facciamo?

**Comment by AndywinXp** [comment]
> But Dustman doesn't like pasta e ceci... Che facciamo?

I'm so angry! And hungry!

**Comment by iFedix** [comment]
Guys I think all of your issues are solved in the upcoming version of dustman. For more issues, ask here o va bene anche a Carpegna quando ci vediamo. Grazie you.

**Comment by Davide-DD** [comment]
Fiuuuuu
